export enum Events {

	LOGIN = "LOGIN",
	REGISTER = "REGISTER",
	LOG = "LOG",
	NOTIFY = "NOTIFY",
	ERROR = "ERROR",
	SUCCESSLOGIN = "SUCCESSLOGIN",
	SUCCESSREGISTER = "SUCCESSREGISTER",
	SETID = "SETID",
	FETCHNAME = "FETCHNAME",
	FETCHUSERS = "FETCHUSERS",
	FETCHCOLOR = "FETCHCOLOR",
	SETDIALOGUEWITH = "SETDIALOGUEWITH",
	FETCHPARTNERDATA = "FETCHPARTNERDATA",
	SEND = "SEND",
	FETCHMESSAGES = "FETCHMESSAGES"

}