SELECT M.TEXT FROM ACTUAL_USERS U
JOIN TEXT_MESSAGES M
ON (U.ID = M.SENDER_ID AND M.RECEIVER_ID = :partnerID)
    OR (U.ID = M.RECEIVER_ID AND M.SENDER_ID = :partnerID)
WHERE U.ID = :id
ORDER BY M.CREATED_AT DESC