SELECT M.TEXT FROM actual_users U
JOIN text_messages M
ON (U.ID = M.SENDER_ID AND M.RECEIVER_ID = :partnerID)
    OR (U.ID = M.RECEIVER_ID AND M.SENDER_ID = :partnerID)
WHERE U.ID = :id
ORDER BY M.CREATED_AT DESC